### ISSUE TITLE
TLS証明書エラーにより画像が表示できない

### ISSUE THREAD

**Issue by otofune** [MissKernel/Misskey#15]
[usercontents](https://usercontents.misskey.xyz)のTLS証明書が期限切れです。
切れていることにより画像がエラーで表示できません。
![image](https://cloud.githubusercontent.com/assets/15062473/13559313/4242f7fc-e456-11e5-8a8e-fcd3a70d766f.png)
[メーン画面](https://misskey.xyz)と[talk](https://talk.misskey.xyz)、[forum](https://forum.misskey.xyz)、[about](https://about.misskey.xyz)は5/15までの証明書なので問題はなさそうですが他のサブドメインがあれば一度確認するべきなのかも知れないです。(logoutは未確認)

[別ドメインに隔離するという提案](https://github.com/MissKernel/Misskey-Web/issues/82)もあり、こちらの為更新を差し控えているのであれば早急に変更頂ければ。

**Comment by syuilo** [comment]
Thanks for reporting! I will update certs.

**Comment by rinsuki** [comment]
本来はcronなどで自動更新するべきなのではないでしょうか。

**Comment by otofune** [comment]
アップデート時にwebrootを指定しておいてあるファイルを表示する、または実行するnginxやapacheなどの一般的なウェブサーバーではないので、恐らくサーバーを止めなければ行けなく自動化が面倒なのではないのかと思われます。
また当初の問題である「TLS証明書により画像が表示できない」は解決されましたのでCloseさせて頂きます。
