### ISSUE TITLE
他サーバーで動いているユーザーをフォローする機能

### ISSUE THREAD

**Issue by rinsuki** [MissKernel/Misskey#18]

**Comment by syuilo** [comment]
？

**Comment by syuilo** [comment]
need details

**Comment by syuilo** [comment]
どのサーバーを利用していようがフォロー出来ると思います

**Comment by rinsuki** [comment]
Misskeyサーバーは誰でも建てられますが、サーバーごとにアカウントを作らないといけないのがネックだと思ったのでサーバーを超えたユーザーのフォローが実現できたらなと
GNU Socialのリモートフォローみたいな感じで

**Comment by syuilo** [comment]
What does GNU Social mean?
データベースが複数に独立していればそうなります

**Comment by syuilo** [comment]
全く別々のデータベースのドキュメントをリンクさせる事は非現実的だと思われます。そもそもMisskeyは個人が動作させることを想定していないので、コアデータベースに複数のサーバーが接続するというケースしか対応しません。
